name: Test Suite Sanity Checking

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 3:42, arbitrarily as a time that's possibly non-busy
    - cron: "42 3 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up nox
        uses: wntrblm/nox@2024.03.02
      - name: Run nox
        run: nox
